### ISSUE TITLE
ProgressCircle rounded ProgressBorder in Android

### ISSUE THREAD

**Issue by MarcorOnline** [vincentgury/XFShapeView#1]
Hello.

Do you think it's possible to insert an option to have a NOT-rounded progress border on Android (like on iOS).

Thanks for your great library!

**Comment by vincentgury** [comment]
Hello @MarcorOnline,

In fact it's an unexpected and unconsistent behavior that I didn't see.

I am not sure I want to add an extra option for such a specific thing so I will probably just make it looking like on iOS. Would you really need such an option?

Thanks for your report.
