### ISSUE TITLE
Xaml usage

### ISSUE THREAD

**Issue by faisal-nstu** [vincentgury/XFShapeView#15]
Is it possible to use this in Xaml code? I tried but couldn't find the right namespace.

**Comment by ironelder** [comment]
xmlns:xfShapeView="clr-namespace:XFShapeView;assembly=XFShapeView"


<xfShapeView:ShapeView ShapeType="ProgressCircle" Opacity="1" Progress="50" IsVisible="True" BorderColor="Transparent" BorderWidth="7" Color="Red" ProgressBorderColor="White" ProgressBorderWidth="5" AbsoluteLayout.LayoutBounds=".5,.5,.5,.5" AbsoluteLayout.LayoutFlags="All">
               
Your Content Here
Label. Entry... etc


</xfShapeView:ShapeView>

**Comment by faisal-nstu** [comment]
This worked perfectly! Thanks!
