### ISSUE TITLE
Progress Circle not rendering in iOS

### ISSUE THREAD

**Issue by bblocher** [vincentgury/XFShapeView#2]
Here is the xaml I'm using
`<xfShapeView:ShapeView  ShapeType="ProgressCircle" 
                              Opacity=".75"
                              Progress="{Binding UploadProgress}" IsVisible="{Binding ShowProgress}"
                              BorderColor="Transparent" BorderWidth="7" Color="Transparent"
                              ProgressBorderColor="White" ProgressBorderWidth="5"
                              AbsoluteLayout.LayoutBounds=".5,.5,.5,.5" AbsoluteLayout.LayoutFlags="All">`

This works great on Android, but nothing renders on iOS (I tried 9.3 and 10). 
I'm a missing an Init() call maybe? Didn't notice any special requirements.

**Comment by vincentgury** [comment]
Add Renderers.Init(); to the AppDelegate like so:

``` csharp
using XFShapeView.iOS;
[...]
public override bool FinishedLaunching(UIApplication app, NSDictionary options)
{
    global::Xamarin.Forms.Forms.Init();

    Renderers.Init();

    LoadApplication(new App());

    return base.FinishedLaunching(app, options);
}
```
