### ISSUE TITLE
Could not load type 'XFShapeView.Droid.ShapeRenderer'

### ISSUE THREAD

**Issue by malokuS** [vincentgury/XFShapeView#3]
Based on the ReadMe.md there is no call for any Init(); but it seems that there should be one because the mono droid cannot load the 'XFShapeView.Droid.ShapeRenderer', or is there any other cause for this error: 

`[ERROR] FATAL UNHANDLED EXCEPTION: System.TypeLoadException: Could not load type 'XFShapeView.Droid.ShapeRenderer' from assembly 'XFShapeView.Droid, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.`

My Environment is:
- Compile Using Android Version: _"Use Latest Platform(Android 7.0(Nougat))"_
- Minimum Android To Target: _"Android 4.0.3(API Level 15-Ice Cream Sandwich)"_ (Tried with API 16 - Same Results!)
- Target Android Version: _"Android 6.0(API Level 23 - Marshmallow)"_
- Xamarin Forms: 2.3.3.152-pre2

On iOS there is no error but no view either.

My ShapeView Implementation:

``` csharp
 var simpleCircle = new ShapeView()
            {
                ShapeType = ShapeType.Circle,
                HeightRequest = 75,
                MinimumHeightRequest = 50,
                WidthRequest = 75,
                MinimumWidthRequest = 50,
                Color = Color.White,
                BorderColor = Color.White,
                Content = new Label
                {
                    Text = "Dummy Text",
                    TextColor = Color.White,
                    FontSize = Device.GetNamedSize(NamedSize.Micro, typeof(Label)),
                    HorizontalOptions = LayoutOptions.Center,
                    VerticalOptions = LayoutOptions.Center,
                    HorizontalTextAlignment = TextAlignment.Center,
                    VerticalTextAlignment = TextAlignment.Center
                }
            };
```

**Comment by vincentgury** [comment]
Hi @malokuS,

I will give a look later today. In the mean time, if you could attach a not working project to the issue, it will make if faster for me to reproduce and correct.

For iOS, did you add the Renderers.Init(); in AppDelegate as the readme file states? I updated the readme with this part this morning (French time), so you may not have seen it.

Did you try the sample project provided with the source code? Is it working?

**Comment by vincentgury** [comment]
You should update Xamarin.Forms package to 2.3.3.163-pre3.

Here is the related fix: https://github.com/xamarin/Xamarin.Forms/pull/406

My Android ViewRenderer doesn't implement **CreateNativeControl** as this abstract/virtual method doesn't exists in Xamarin.Forms last stable version (2.3.2.127)

**Comment by malokuS** [comment]
Okay that did the work, thanks. 

BUT you shouldn't close an issue without first confirming that it has a fix!

Regards,
malokuS
