### ISSUE TITLE
Content Label Text Binding

### ISSUE THREAD

**Issue by ryanherman** [vincentgury/XFShapeView#5]
I tried a few ways to update the Text on the Content, event set Binding to a value and it doesn't update.  Am I doing something incorrect or this doesn't work?

**Comment by ryanherman** [comment]
I'm starting to think it has to do w/ the Hamburger Menu in Xamarin.Forms not updating my Binding correctly...

**Comment by vincentgury** [comment]
OK, keep me informed in case the problem comes from XFShapeView.
