### ISSUE TITLE
iOS : ShapeRenderer.Init() is not exposed 

### ISSUE THREAD

**Issue by tssutha** [vincentgury/XFShapeView#9]
Thanks for awesome plugin to to draw some custom shapes, it is really cool. I have tested on Android, but unable to test it on iOS , because Init function is not available in iOS, I checked the implementation, the function is defined in iOS project as a Static Method, but not available when I try to use it throught Nuget package manager. I will be nice if you could fix this issue.  or am I missing some setup?

**Comment by rmenezes** [comment]
@tssutha are you using the nuget version?

**Comment by rashidovich** [comment]
@rmenezes yes.

**Comment by rmenezes** [comment]
@tssutha try to use the github version. The nuget version is outdated.

**Comment by henningms** [comment]
I'm not sure if the latest version has gone through to "stable". Remember to enable pre-release NuGets to get the latest version

**Comment by kmccmk9** [comment]
@henningms, Thank you for the tip!

**Comment by fgiacomelli** [comment]
same problem for me, why it's not released to nuget store?

**Comment by rmenezes** [comment]
@fgiacomelli no idea. I already sent a pull request with this fix but I'm still waiting for this.

**Comment by henningms** [comment]
Yeah, hopefully @vincentgury can accept and publish a new version on NuGet or we have to fork and release a new one ourselves  although I hope we can avoid that!

**Comment by vincentgury** [comment]
Sorry for the delay, I started a new job and have been quite busy lately.

Will try to push a new nuget package this week.

**Comment by vincentgury** [comment]
@henningms, the new version in published, enjoy!
